### ISSUE TITLE
Generating keys in tests is very slow

### ISSUE THREAD

**Issue by wearpants** [EFForg/cryptobot-email#24]
Generating a keypair in tests is extremely slow. This is related to #18 & #23.

Ideally, we reduce # of tests that generate keys in the first place. At a quick glance, the only test that seems to _require_ generating a new key is `GnuPGTest.test_gen_key`.

Key generation is slow b/c the kernel lacks entropy (this is often a problem on servers & VMs without a lot of I/O). Possible approaches:
- run `find /` in a background process to thrash the disk. Ick.
- reduce keypair size (need more research)
- configure things to use an alternate source of entropy (hardware RNG, whatever)

Alternately, the slow tests could be moved to a separate file, so that they can be run selectively.

**Comment by mfb** [comment]
would running haveged in the test environment be enough of a solution?

**Comment by wearpants** [comment]
Cool, that did the trick :-). I'll make a note in the docs

http://www.issihosts.com/haveged/

**Comment by garrettr** [comment]
Additionally, you could consider using a smaller key size (say RSA-1024) for tests _only_. These are much faster to generate than 2048 or 4096 bit keys. We do this for the [Securedrop unit tests](https://github.com/freedomofpress/securedrop/blob/master/securedrop/test.py#L19).
