### ISSUE TITLE
"Big hammer" unsubscribe

### ISSUE THREAD

**Issue by dannyob** [EFForg/cryptobot-email#26]
Cryptobot needs an unsubscribe link that ensures you never get an email again from it. This unsubscribe link needs to be at the bottom of every mail.

**Comment by liliakai** [comment]
How should we handle this on the backend? mysql or postgres database?

**Comment by liliakai** [comment]
Fixed in #33. Unsubscribe link takes you to unsubscribe form on cryptobot.org.
