### ISSUE TITLE
Support reading from Maildir directly instead of IMAP

### ISSUE THREAD

**Issue by dtauerbach** [EFForg/cryptobot-email#4]
Right now exim puts email into Maildir format. We can use Python mailbox class to read this directly, instead of requiring IMAP.

**Comment by micahflee** [comment]
I made it so after responding to an email the bot deletes it in IMAP, but I haven't implemented this for Maildirs. Can you implement it? https://github.com/EFForg/OpenPGPBot/blob/master/bot.py#L64

**Comment by dtauerbach** [comment]
Yes, I'm on it. The Maildir implementation seems to have some problem with parsing email that I need to investigate.

**Comment by dtauerbach** [comment]
There is now a hack to work with Maildir, which had a parsing problem. tl;dr: str(msg) where msg is a Message won't give you the full message.

The bot is working on openpgpbot.eff.org, though isn't being run on a cron or anything right now.
